todolist/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(30))
    description = db.Column(db.String(1000))
    complete = db.Column(db.Boolean, default=False)
    created = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return self.title


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    tasks = db.relationship('Task', lazy=True, backref='tasks')

todolist/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
import secrets
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = secrets.token_hex(16)
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    from .models import User, Task

    create_database(app)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_database(app):
    if not path.exists('todolist/' + DB_NAME):
        db.create_all(app=app)
        print("Created Database!")

todolist/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('views.task_list'))

    if request.method == "POST":
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            if check_password_hash(user.password, password):
                flash("Logged in Successfully!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.task_list'))
            else:
                flash("Incorrect password, try again", category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged Out!', category='success')
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():

    if current_user.is_authenticated:
        return redirect(url_for('views.task_list'))

    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()

        if user:
            flash("Email already exists.", category='error')

        elif len(first_name) < 2:
            flash("First name must be greater than 1 characters.", category='error')

        elif password1 != password2:
            flash("Passwords don\'t match.", category='error')

        elif len(password1) < 4:
            flash("Password must be at least 4 characters long.", category='error')

        else:
            new_user = User(email=email, password=generate_password_hash(password1, method='sha256'), first_name=first_name)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Account created!", category='success')
            return redirect(url_for('views.task_list'))

    return render_template("sign_up.html", user=current_user)

todolist/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user, login_required
from .models import Task
from . import db

views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def task_list():
    count = Task.query.filter_by(user_id=current_user.id, complete=False).count()
    plural = True if count > 1 else False
    tasks = current_user.tasks
    search_input = ''

    if request.method == "POST":
        search = request.form.get('search-area')
        search_input = search
        result = Task.query.filter(Task.title.like(f'%{search}%'), Task.user_id == current_user.id).all()
        tasks = result

    return render_template("task_list.html", user=current_user, plural=plural, count=count, tasks=tasks,
                           search_input=search_input)


@views.route('/task-create', methods=['GET', 'POST'])
@login_required
def task_form():

    if request.method == "POST":
        title = request.form.get('title')
        description = request.form.get('description')
        complete = request.form.get('complete')

        if complete:
            complete = True

        new_task = Task(title=title, description=description, complete=complete, user_id=current_user.id)
        db.session.add(new_task)
        db.session.commit()
        flash("Task created!", category='success')
        return redirect(url_for('views.task_list'))

    return render_template("task_form.html", user=current_user)


@views.route('/task-delete/<int:id>', methods=['GET', 'POST'])
@login_required
def task_delete(id):
    task = Task.query.filter_by(id=id).first()
    if request.method == "POST":
        db.session.delete(task)
        db.session.commit()
        flash("Task Deleted!", category='success')
        return redirect(url_for("views.task_list"))

    return render_template("task_confirm_delete.html", task=task)


@views.route('/task-update/<int:id>', methods=['GET', 'POST'])
@login_required
def task_update(id):
    task = Task.query.filter_by(id=id).first()
    if request.method == "POST":
        task.title = request.form.get('title')
        task.description = request.form.get('description')
        complete = request.form.get('complete')

        if complete:
            complete = True
        else:
            complete = False

        task.complete = complete
        db.session.commit()
        flash("Task Updated!", category='success')
        return redirect(url_for("views.task_list"))

    return render_template("task_update.html", task=task)

todolist/templates/login.html
{% extends 'main.html' %}
{% block content %}

    <div class="header-bar">
        <h1>로그인 화면</h1>
    </div>

    <div class="card-body">
        <form action="" method="post">
            <label>이메일 주소:</label>
            <input type="email" name="email">

            <label>패스워드:</label>
            <input type="password" name="password">

            <input style="margin-top: 10px;" class="button" type="submit" value="Login">
        </form>
        <p>계정이 없습니까? → <a href="{{ url_for('auth.sign_up')}}">Register</a></p>
    </div>
{% endblock %}

todolist/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To Do List</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

</head>
<body>

    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class='flashes'>
                {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
                </ul>
    </div>

    <div class="container">



            {% endif %}
        {% endwith %}

        {% block content %}
        {% endblock %}
    </div>

</body>
</html>

todolist/templates/sign_up.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <h1>회원가입</h1>
</div>

<div class="card-body">
    <form method="POST">

        <label>성</label>
        <input type="text" name="firstName">

        <label>이메일 주소</label>
        <input type="email" name="email">

        <label>패스워드</label>
        <input type="password" name="password1">

        <label>패스워드 재입력</label>
        <input type="password" name="password2">

        <input style="margin-top:10px ;" class="button" type="submit" value="Register">
        <input style="margin-top:10px ;" class="button" type="reset" value="Reset">
    </form>
    <p>이미 가입된 계정이 있습니까? → <a href="}">Login</a></p>
</div>

{% endblock %}{{ url_for('auth.login') }}

todolist/templates/task_confirm_delete.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <a href="{{ url_for('views.task_list') }}">&#8593;Go Back</a>
</div>

<div class="card-body">
    <form action="" method="post">
        <p>Are You sure you want to delete this task? "{{task}}"</p>
        <input class="button" type="submit" value="delete">
    </form>
</div>

{% endblock %}

todolist/templates/task_form.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <a href="{{ url_for('views.task_list') }}">&#8592; Back</a>
</div>

  <div class="card-body">
      <form action="" method="post">

          <label>Title</label>
          <input type="text" name="title">

          <label>Description</label>
          <textarea rows="5" name="description"></textarea>

          <label>Complete<input type="checkbox" name="complete"></label>

          <input style="margin-top:10px;" class="button" type="submit" value="Submit">
      </form>
  </div>

{% endblock %}

todolist/templates/task_list.html
{% extends 'main.html' %}
{% block content %}
{% if current_user.is_authenticated %}
<div class="header-bar">
        <div>
            <h1>Hello {{current_user.first_name|title}}</h1>
            <h3 style="margin:0">You have <i>{{ count }}</i> incomplete
                {% if plural %}
                tasks
                {% else %}
                task
                {% endif %}
            </h3>
        </div>

        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}">Logout</a>
        {% else %}
        <a href="#">Login</a>
        {% endif %}
    </div>

    <div id="search-add-wrapper">
        <form action="" method="post" style="margin-top: 20px; display: flex;">
            <input type="text" name="search-area" value="{{search_input}}">
            <input class="button" type="submit" value="Search">
        </form>
        <a id="add-link" href="{{ url_for('views.task_form') }}">&#x2b;</a>
    </div>

    <div class="task-items-wrapper">
        {% for task in tasks %}
            <div class="task-wrapper">
                {% if task.complete %}
                    <div class="task-title">
                        <div class="task-complete-icon"></div>
                        <i><s><a href="{{ url_for('views.task_update', id=task.id) }}">{{task.title}}</a></s></i>
                    </div>
                <a class="delete-link" href="{{ url_for('views.task_delete', id=task.id) }}">&#215;</a>
                {% else %}
                    <div class="task-title">
                        <div class="task-incomplete-icon"></div>
                        <a href="{{ url_for('views.task_update', id=task.id) }}">{{task.title}}</a>
                    </div>
                <a class="delete-link" href="{{ url_for('views.task_delete', id=task.id) }}">&#215;</a>
                {% endif %}

            </div>
        {% else %}
        <h3 style="margin-left:10px;">No Items in List</h3>
        {% endfor %}
    </div>

{% endif %}

{% endblock %}

todolist/templates/task_update.html
{% extends 'main.html' %}

{% block content %}

<div class="header-bar">
    <a href="{{ url_for('views.task_list') }}">&#8592; Back</a>
</div>

  <div class="card-body">
      <form action="" method="post">

          <label>Title</label>
          <input type="text" name="title" value="{{ task.title }}">

          <label>Description</label>
          <textarea rows="5" name="description">{{ task.description }}</textarea>

          <label>Complete<input type="checkbox" name="complete" checked></label>

          <input style="margin-top:10px;" class="button" type="submit" value="Submit">
      </form>
  </div>

{% endblock %}